name: Extension CI

on:
  push:
    branches: [main, develop]
    paths:
      - "extension/**"
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/extension_ci.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "extension/**"
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/extension_ci.yml"

jobs:
  extension-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # For some reason, `pnpm run format:check` blows up in CI if we let
      # the version here match the one that we are running (pnpm 9.0.0 as of this writing),
      # and if we leave it at 8, things are ok.
      # XXX once we upgrade to pnpm 10, we should try making this match
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install all dependencies
        run: pnpm install --frozen-lockfile

      - name: Build core package
        run: pnpm run build

      - name: Check extension formatting
        working-directory: ./extension
        run: pnpm run format:check

      - name: Run extension type check
        working-directory: ./extension
        run: pnpm run typecheck

      - name: Run extension tests
        working-directory: ./extension
        run: pnpm test

      - name: Build extension for Firefox
        working-directory: ./extension
        run: pnpm run build:firefox

      - name: Build extension for Chrome
        working-directory: ./extension
        run: pnpm run build:chrome
